apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: logging
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push
        batchwait: 1s
        batchsize: 102400

    scrape_configs:
    - job_name: static-logs
      static_configs:
      - targets: [localhost]
        labels:
          job: log-generator
          __path__: /var/log/pods/logging_log-generator-649c6cc8c4-z24kp_45b57714-b773-4878-abd0-f60d925a9db5/generator/0.log