apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: logging
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
      - name: promtail
        image: grafana/promtail:2.8.4
        args:
        - -config.file=/etc/promtail/promtail.yaml
        - -log.level=debug
        - -print-config-stderr
        - -client.external-labels=host=${HOSTNAME}
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: false
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
        - name: pods
          mountPath: /var/log/pods
          readOnly: false
        - name: containers
          mountPath: /var/lib/containerd
          readOnly: true
        ports:
        - containerPort: 9080
          name: http-metrics
      volumes:
      - name: config
        configMap:
          name: promtail-config
      - name: pods
        hostPath:
          path: /var/log/pods
          type: Directory
      - name: containers
        hostPath:
          path: /var/lib/containerd
          type: Directory